/** 对照key：显示名称 */
export default {
    "RenderCell": "RenderCell 渲染单元",
    "/examples/RenderCell/base": "基本用法",
    "/examples/RenderCell/inForm": "在表单中使用",
    "/examples/RenderCell/item": "渲染单元API",
    "/examples/RenderCell/slotExpRender": "render 自定义渲染",
    "/examples/RenderCell/slotExpConfig": "全局自定义组件",
    "/examples/RenderCell/elementPlus": "elementPlus 组件库支持",
    "RenderCellExtend": "RenderCell 内置扩展组件",
    "/examples/RenderCellExtend/selectMore": "select-more 分页下拉选择器",
    "/examples/RenderCellExtend/exportButton": "export 导出按钮",
    "/examples/RenderCellExtend/rangeSelect": "range-select 范围选择器",
    "Bussiness": "Bussiness 业务组件",
    "/examples/Bussiness/ISearch": "ISearch 组合搜索",
    "/examples/Bussiness/IForm": "IForm 动态表单",
    "/examples/Bussiness/IDialogForm":"IDialogForm 弹窗表单",
    "/examples/Bussiness/ITable": "ITable 动态表格",
    "/examples/Bussiness/IPage": "IPage 组合页面",
    "Config": "Config 全局配置",
    "/examples/Config/index": "配置引用",
    "/examples/Config/config": "全部配置参数说明",
    "/examples/Config/searchConfig": "ISearch 配置参数",
}